version: "3.2"
services:
   nginx:
       container_name: ci4_nginx
       image: nginx:1.17.8-alpine
       restart: always
       ports:
           - ${NGINX_PORT}:80
       volumes:
           - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
           - .:/php_app
       links:
           - php_app

   php_app:
       build: docker/php_app
       container_name: ci4_php_app
       restart: always
       volumes:
           - .:/php_app